### ISSUE TITLE
Snackbar & Pop-Ups

### ISSUE THREAD

**Issue by waterrmalann** [waterrmalann/kards#11]
# Better Alerts

This issue proposes an enhancement to the user experience of the app in two ways.

- Replace the regular JavaScript `alert()` alerts with much more user-friendly custom styled snackbar notifications instead.
- Add a pop-up confirmation box when the user wishes to do something destructive like delete a board.

## Snackbar

Toast-like notifications that doesn't disrupt the flow of the app while providing warnings, alerts, and other information.

**Potential Implementation:** A parent element has to be defined that is positioned at the bottom left/right or top left/right corner of the screen. It should have a flexbox flex-direction of column to align downwards. When an alert is sent, a notification element is appended to the parent element with a timeout set to 2 or 3 seconds to automatically dispose the element and removes it from the DOM.

## Pop-Up Confirmation

Simple pop-ups to get a confirmation from the user prior to destructive activities that may have been initiated accidentally.

Destructive activities include:

- Deleting a board.
- Deleting a card.
- Clearing a card.
- Changes in preferences (not implemented yet, will be after #4 )

**Potential Implementation:** A modal could be used to show the pop-up with the buttons passing the information back to whatever function that called for the pop-up.  An alternative is to use JavaScript's `confirm()`, it is quite ugly but way better than no confirmation at all.

**Comment by maliksenpai** [comment]
I will work on Pop-up

**Comment by waterrmalann** [comment]
Snackbar has been implemented as of PR #12 

Confirmation dialog boxes have been added in PR #15
